"Fixed local wait issue and added continue shopping test on checkout"
SohamQAKrish/Bateel_Automation pull request #2
Opened 2024-04-15 12:18 UTC by KashyapDave95

"Fixed local wait issue and added continue shopping test on checkout"

2024-04-30 04:23 UTC, SohamQAKrish requested changes
Do not push all the details. Remove unnecessary files from here.

2024-04-30 16:47 UTC, KashyapDave95 commented on src/main/java/common/UtilitiesCommon.java
> +
Removed space.

2024-04-30 16:50 UTC, KashyapDave95 commented on src/main/java/page/bateel/BateelGuestCheckoutPage.java
> +
Removed spaces.

2024-05-24 07:30 UTC, SohamQAKrish commented
Closing this PR as we can not commit 70 files. Re-raise the PR after making the changes.

@KashyapDave95  @rammohan-krish-QA

2024-05-24 07:30 UTC, closed without merging